# Generated by Django 4.2.17 on 2025-01-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotion_updated_at_alter_promotion_end_date_and_more'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='promotions',
            field=models.ManyToManyField(related_name='customers', to='promotions.promotion'),
        ),
    ]
